{"error": "*****Your inputs seem to be fine. It might be some internal errors from our server. Wait for some time and try again. If you still have problems, please get in touch with us. ", "original_error": "[Errno 2] No such file or directory: '/data/chem/passer/static/results/M154I_auto_out/pockets/pocket1_atm.pdb'"}